In [ ]:
print('hello')

hello


In [ ]:
a=12
b1=13
print(a-b1)

-1


In [ ]:
print('Umesh')
print(a / b1)

Umesh
0.9230769230769231


In [ ]:
q=6
q ==6
print(q)

6


In [ ]:
age = 20
if age> 18:
  print('you can drive')

you can drive


In [ ]:
mark = 95
if mark <= 70:
  print('first class')
else:
    print('second class')

second class


In [ ]:
mark = 65
if mark >= 90:
  print('first class')
elif mark > 80:
  print('Second class')
elif mark >= 70:
  print('Second class')
else:
  print('D class')

D class


In [ ]:
print('Hello Umesh')
print('Hello Umesh')
print('Hello Umesh')
print('Hello Umesh')
print('Hello Umesh')
print('Hello Umesh')

Hello Umesh
Hello Umesh
Hello Umesh
Hello Umesh
Hello Umesh


In [ ]:
for d in range (7):
  print(d)

0
1
2
3
4
5
6


In [ ]:
for d in range (1, 11):
  print(d * 2)

2
4
6
8
10
12
14
16
18
20


In [ ]:
for d in range (1, 11):
  print(d)

1
2
3
4
5
6
7
8
9
10


In [ ]:
for i in range (10):
  print('Hello')


Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello


In [ ]:
for i in range(2, 21, 2):
  print(i)

2
4
6
8
10
12
14
16
18
20


In [ ]:
a = ['Pune', 'Mumbai', 'Delhi', 'Banglore', 'Pune']
print('original list', a)

a.append('Delhi')
print('adding city at last', a)



original list ['Pune', 'Mumbai', 'Delhi', 'Banglore', 'Pune']
adding city at last ['Pune', 'Mumbai', 'Delhi', 'Banglore', 'Pune', 'Delhi']


In [ ]:
A = ['Pune', 'Mumbai', 'Delhi', 'Banglore', 'Nagpur']
print('List', A)

A[0]= 'Wardha'
print(A)


List ['Pune', 'Mumbai', 'Delhi', 'Banglore', 'Nagpur']
['Wardha', 'Mumbai', 'Delhi', 'Banglore', 'Nagpur']


In [ ]:
b = [2,3,4,5,6,7,8,9,10]
a=1
for n in b:
  a=a*n
print(a)

3628800


In [ ]:
country= ['Afghanistan', 'UK', 'Algeria', 'Andorra', 'USA', 'Japan']

for con in country:
  print(con)


Afghanistan
UK
Algeria
Andorra
USA
Japan


In [ ]:
# Slicing
country= ['Afghanistan', 'UK', 'Algeria', 'Andorra', 'USA', 'Japan']
print(country[1:3])

['UK', 'Algeria']


In [ ]:
country= ['Afghanistan', 'UK', 'Algeria', 'Andorra', 'USA', 'Japan']
print(country[0:4])


['Afghanistan', 'UK', 'Algeria', 'Andorra']


In [ ]:
country= ['Afghanistan', 'UK', 'Algeria', 'Andorra', 'USA', 'Japan']
print(country[-4:-1])

['Algeria', 'Andorra', 'USA']


In [ ]:
country= ['Afghanistan', 'UK', 'Algeria', 'Andorra', 'USA', 'Japan']
print(country[4:-1])

['USA']


In [ ]:
country= ['Afghanistan', 'UK', 'Algeria', 'Andorra', 'USA', 'Japan']
print(country[3:-1])

['Andorra', 'USA']


In [ ]:
Fruits= ['Mango', 'Appale', 'Grapes', 'Banana', 'Orange', 'Cherry', 'Kiwi']

for con in Fruits:
  print(con)

Mango
Appale
Grapes
Banana
Orange
Cherry
Kiwi


In [ ]:
Fruits= ['Mango', 'Appale', 'Grapes', 'Banana', 'Orange', 'Cherry', 'Kiwi']
print(Fruits[3:-1])
print(Fruits[1:3])
print(Fruits[0:5])
print(Fruits[-4:-1])


['Banana', 'Orange', 'Cherry']
['Appale', 'Grapes']
['Mango', 'Appale', 'Grapes', 'Banana', 'Orange']
['Banana', 'Orange', 'Cherry']


In [ ]:
Fruits= ['Mango', 'Appale', 'Grapes', 'Banana', 'Orange', 'Cherry', 'Kiwi']
print(Fruits[1:3])

['Appale', 'Grapes']


In [ ]:
import numpy as np
a = np.array ([1,2,3,4])
b = np.array ([5,6,7,8])
print (a*b)

[ 5 12 21 32]


In [ ]:
import numpy as np
a = np.array ([1,2,3,4,5])
b = np.array ([6,7,8,9,10])
print (a/b)

[0.16666667 0.28571429 0.375      0.44444444 0.5       ]


In [ ]:
import numpy as np
a = np.array ([1,2,3,4,5])
b = np.array ([6,7,8,9,10])
print (a-b)

[-5 -5 -5 -5 -5]


In [ ]:
import numpy as np
a = np.array ([1,2,3,4,5])
b = np.array ([6,7,8,9,10])
print (a+b)

[ 7  9 11 13 15]


In [ ]:
import numpy as np
a = np.array ([1,2,3,4,5])
b = np.array ([6,7,8,9,10])
print (a//b)

[0 0 0 0 0]


In [ ]:
Bp = 130
if Bp <= 70:
  print('High blood pressure')
else:
    print('Low blood pressure')

Low blood pressure


In [ ]:
Bp = 130
if Bp >= 70:
  print('High blood pressure')
else:
    print('Low blood pressure')

High blood pressure


In [ ]:
Bp = 100
if Bp  >= 90:
  print('High blood pressure')
elif Bp  >= 80:
  print('Low blood pressure')
elif Bp  >= 70:
  print('Low blood pressure')
else:
  print('Bp Result')

High blood pressure


In [ ]:
Bp = 100
if Bp  <= 90:
  print('High blood pressure')
elif Bp  <= 80:
  print('Low blood pressure')
elif Bp  <= 70:
  print('High blood pressure')
else:
  print('Low blood pressure')

Low blood pressure


In [ ]:
suger = 240
if suger >= 140:
 print ('High blood suger')

High blood suger


In [ ]:
suger = 140
if suger <= 140:
 print ('low blood suger')

low blood suger


In [ ]:
import numpy as np
a = np.random.randint(50)
print(a)


37


In [ ]:
#Sum
a= np.array([10,20,30,40,50])
print(np.sum(a))

150


In [ ]:
#average (mean)
print(np.mean(a))

30.0


In [ ]:
#maximum
print(np.max(a))

50


In [ ]:
#minimum
print(np.min(a))

10


In [ ]:
#median
print(np.median(a))

30.0


In [ ]:
#argmax- index of max value
print(np.argmax(a))

4


In [ ]:
#argmax- index of min value
print(np.argmin(a))

0


In [ ]:
#prod - produc of element
print(np.prod(a))

12000000


In [ ]:
a= np.array([100,200,300,400,500])
print(np.sum(a))
print(np.mean(a))
print(np.max(a))
print(np.min(a))
print(np.median(a))
print(np.argmax(a))
print(np.argmin(a))
print(np.prod(a))

1500
300.0
500
100
300.0
4
0
1200000000000


In [ ]:
def add(a , b):
  print(a + b)

def sub(a , b):
  print(a - b)

add(20,25)
sub(20,55)


45
-35


In [ ]:
def greeting (name = 'user'):
   print('hello', name)

   greeting()

In [ ]:
def even(num):
  if num%2 == 0:
    print('even number')
  else:
    print('odd number')

even(7)

odd number


In [ ]:
def cube(num):
  a = num*num*num
  print(a)

cube(7)


343


In [ ]:
class student:
  def display(self):
    print('display')

s1 = student()
s1.display()

display


In [ ]:
class company:

 name = 'TCS'
 exprienc = 7

company1= company()
print(company1. name)
print(company1. exprienc)




TCS
7


In [ ]:
class person:
    def set_details(self):
      self.name = 'umesh'
      self.age = 17

    def show_details(self):
      print('name', self.name)
      print('age', self.age)

class student(person):
    def study(self):
      print(self.name,'is studying')

s1 = student()
s1.set_details()
s1.study()
s1.show_details()



umesh is studying
name umesh
age 17


In [ ]:
class person:
    def set_details(self):
        self.name = "umesh"
        self.age = 17

    def show_details(self):
        print("name", self.name)
        print("age", self.age)

class student(person):
    def study(self):
        print(self.name,"is studying")

s1 = student()
s1.set_details()
s1.study()
s1.show_details()

umesh is studying
name umesh
age 17


In [ ]:
# Multi level inheritance

class fruitsmarket:
  def hometown(self):
    print("fruitsmarket class and hometown")

class parent(fruitsmarket):
  def appale(self):
    print("parent class with appale")

class child(parent):
  def orange(self):
    print("child class with orange")

class grandchild(child):
  def grapes(self):
    print("this is grandchild class with grapes")

a1 = grandchild()
a1.appale()

a1.orange()
a1.grapes()

parent class with appale
child class with orange
this is grandchild class with grapes


In [ ]:
# multiple inheritance

class father:
  def homeking(self):
    print("homeking function of  father class")

class mother:
  def homemqueen(self):
    print("homequeen function of mother class")

class child(father,mother):
  def own(self):
    print("this is child class in multiple")

a1 =child()

a1.homeking()
a1.homemqueen()
a1.own()

homeking function of  father class
homequeen function of mother class
this is child class in multiple


In [ ]:
# Hierachical inheritance

class father:
  def homeking(self):
    print("homeking function of  father class")

class child1(father):
  def quality(self):
    print("child quality")

class child2 (father):
  def dailytask(self):
    print("child2 dailytask")

a1 = child1()
a2 = child2()
a1.homeking()








homeking function of  father class


In [ ]:
#Hybrid inheritance

class father:
  def homeking(self):
    print("homeking function of  father class")

class mother:
  def homemqueen(self):
    print("homequeen function of mother class")

class child1(father, mother):
  def quality(self):
    print("child quality")

class child2 (child1):
  def dailytask(self):
    print("child2 dailytask")




a1.homeking()
a1.quality()
a1 = child1()
a2 = child2()



homeking function of  father class
child quality


1) Find unique disease in trial data set.
2) count how many disease present entry data set.
3) check cancer is there then updated with cancer-1.

In [ ]:
# Find unique disease in trial data set.

a= ["COVID-19", "Common Cold", "Flu", "Tuberculosis" , "Diabetes", "AIDS", "Malaria", "Measles", "Diabetes", "Heart Disease", "Cancer", "Alzheimer's Disease", "Pneumonia", "Hepatitis", "Stroke", "Asthma" ]
n= set(a)
print(n)
b=(list(n))
print(b)

{'Flu', "Alzheimer's Disease", 'Asthma', 'Diabetes', 'Pneumonia', 'Malaria', 'Stroke', 'COVID-19', 'Measles', 'Tuberculosis', 'Heart Disease', 'Hepatitis', 'AIDS', 'Common Cold', 'Cancer'}
['Flu', "Alzheimer's Disease", 'Asthma', 'Diabetes', 'Pneumonia', 'Malaria', 'Stroke', 'COVID-19', 'Measles', 'Tuberculosis', 'Heart Disease', 'Hepatitis', 'AIDS', 'Common Cold', 'Cancer']


In [ ]:
# count how many disease present entry data set.

a= ["COVID-19", "Common Cold", "Flu", "Tuberculosis" , "Diabetes", "AIDS", "Malaria", "Measles", "Diabetes", "Heart Disease", "Cancer", "Alzheimer's Disease", "Pneumonia", "Hepatitis", "Stroke", "Asthma" ]
count=0
for i in a:
 count+=1
print(count)


16


In [ ]:
# check cancer is there updated with cancer-1.

a= ["COVID-19", "Common Cold", "Flu", "Tuberculosis" , "Diabetes", "AIDS", "Malaria", "Measles", "Diabetes", "Heart Disease", "Cancer", "Alzheimer's Disease", "Pneumonia", "Hepatitis", "Stroke", "Asthma" ]
a[10]= "cancer-1"
print(a)

['COVID-19', 'Common Cold', 'Flu', 'Tuberculosis', 'Diabetes', 'AIDS', 'Malaria', 'Measles', 'Diabetes', 'Heart Disease', 'cancer-1', "Alzheimer's Disease", 'Pneumonia', 'Hepatitis', 'Stroke', 'Asthma']


In [ ]:
a= ["COVID-19", "Common Cold", "Flu", "Tuberculosis" , "Diabetes", "AIDS", "Malaria", "Measles", "Diabetes", "Heart Disease", "Cancer", "Alzheimer's Disease", "Pneumonia", "Hepatitis", "Stroke", "Asthma" ]
b=(list(a))
print(b)

['COVID-19', 'Common Cold', 'Flu', 'Tuberculosis', 'Diabetes', 'AIDS', 'Malaria', 'Measles', 'Diabetes', 'Heart Disease', 'Cancer', "Alzheimer's Disease", 'Pneumonia', 'Hepatitis', 'Stroke', 'Asthma']


In [ ]:
age = 65
BMI = 25

if age >=45:
  print("person eligbility for CT")
elif BMI <23:
  print("person eligbility for CT")

person eligbility for CT


In [ ]:
# Multi level inheritance

class asthma:
  def copd(self):
    print("asthma class of copd")

class diagnosis(asthma):
  def salbutamol(self):
    print("salbutamol drug use for asthma ")

class symptom(diagnosis):
  def oxygen(self):
    print("Oxygen use for asthma")

class sing(symptom):
  def treatment(self):
    print("This is all sign and symptom with tratment")

a1 = sing()
a1.salbutamol()

a1.oxygen()
a1.treatment()

salbutamol drug use for asthma 
Oxygen use for asthma
This is all sign and symptom with tratment


In [ ]:
import pandas as pd

a = ["shaaz", "reshma", "nitu", "umesh"]

var1 = pd.Series(a, index= ["name1","name2","name3","name4"])
print(var1)

name1     shaaz
name2    reshma
name3      nitu
name4     umesh
dtype: object
